// <auto-generated />
using System;
using ErpBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErpBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423055958_GrantProductCreateToKho")]
    partial class GrantProductCreateToKho
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ErpBackend.Entities.AlertNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<bool>("IsRead")
                        ;

                    b.Property<string>("Message")
                        .IsRequired()
                        ;

                    b.Property<string>("Severity")
                        .IsRequired()
                        ;

                    b.Property<string>("Title")
                        .IsRequired()
                        ;

                    b.Property<string>("Type")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.ToTable("AlertNotifications");
                });

            modelBuilder.Entity("ErpBackend.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int?>("BranchId")
                        ;

                    b.Property<string>("Name")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "K? toán kho"
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            Name = "Sales Hà N?i"
                        });
                });

            modelBuilder.Entity("ErpBackend.Entities.GroupPermission", b =>
                {
                    b.Property<int>("GroupId")
                        ;

                    b.Property<int>("PermissionId")
                        ;

                    b.HasKey("GroupId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("GroupPermissions");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            GroupId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            GroupId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            GroupId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            GroupId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            GroupId = 2,
                            PermissionId = 7
                        });
                });

            modelBuilder.Entity("ErpBackend.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int?>("BranchId")
                        ;

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        ;

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        ;

                    b.Property<DateTime>("DueDate")
                        ;

                    b.Property<DateTime>("InvoiceDate")
                        ;

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        ;

                    b.Property<decimal>("PaidAmount")
                        ;

                    b.Property<string>("Status")
                        .IsRequired()
                        ;

                    b.Property<decimal>("TotalAmount")
                        ;

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ErpBackend.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int>("InvoiceId")
                        ;

                    b.Property<int>("ProductId")
                        ;

                    b.Property<int>("Quantity")
                        ;

                    b.Property<decimal>("UnitPrice")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("ErpBackend.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<decimal>("Amount")
                        ;

                    b.Property<int>("InvoiceId")
                        ;

                    b.Property<DateTime>("PaymentDate")
                        ;

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        ;

                    b.Property<string>("ProcessedBy")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ErpBackend.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Description")
                        .IsRequired()
                        ;

                    b.Property<string>("Name")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Xem s?n ph?m",
                            Name = "product.view"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Thêm s?n ph?m",
                            Name = "product.create"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Duy?t hóa don",
                            Name = "invoice.approve"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Xu?t báo cáo",
                            Name = "report.export"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nh?p kho",
                            Name = "stock.import"
                        },
                        new
                        {
                            Id = 6,
                            Description = "T?o hóa don",
                            Name = "invoice.create"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Thanh toán",
                            Name = "invoice.payment"
                        });
                });

            modelBuilder.Entity("ErpBackend.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int>("MinStockThreshold")
                        ;

                    b.Property<string>("Name")
                        .IsRequired()
                        ;

                    b.Property<decimal>("Price")
                        ;

                    b.Property<decimal>("PurchasePrice")
                        ;

                    b.Property<int>("Stock")
                        ;

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ErpBackend.Entities.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        ;

                    b.Property<int>("ProductId")
                        ;

                    b.Property<int>("Quantity")
                        ;

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        ;

                    b.Property<string>("Type")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("ErpBackend.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int?>("BranchId")
                        ;

                    b.Property<string>("Password")
                        .IsRequired()
                        ;

                    b.Property<string>("Role")
                        .IsRequired()
                        ;

                    b.Property<string>("Username")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            Password = "123",
                            Role = "Sales",
                            Username = "sales_hn"
                        },
                        new
                        {
                            Id = 3,
                            Password = "123",
                            Role = "User",
                            Username = "kho_user"
                        });
                });

            modelBuilder.Entity("ErpBackend.Entities.UserGroup", b =>
                {
                    b.Property<int>("UserId")
                        ;

                    b.Property<int>("GroupId")
                        ;

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroups");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            GroupId = 2
                        },
                        new
                        {
                            UserId = 3,
                            GroupId = 1
                        });
                });

            modelBuilder.Entity("ErpBackend.Entities.GroupPermission", b =>
                {
                    b.HasOne("ErpBackend.Entities.Group", "Group")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpBackend.Entities.Permission", "Permission")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("ErpBackend.Entities.InvoiceItem", b =>
                {
                    b.HasOne("ErpBackend.Entities.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpBackend.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ErpBackend.Entities.Payment", b =>
                {
                    b.HasOne("ErpBackend.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("ErpBackend.Entities.StockTransaction", b =>
                {
                    b.HasOne("ErpBackend.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ErpBackend.Entities.UserGroup", b =>
                {
                    b.HasOne("ErpBackend.Entities.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpBackend.Entities.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErpBackend.Entities.Group", b =>
                {
                    b.Navigation("GroupPermissions");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("ErpBackend.Entities.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ErpBackend.Entities.Permission", b =>
                {
                    b.Navigation("GroupPermissions");
                });

            modelBuilder.Entity("ErpBackend.Entities.User", b =>
                {
                    b.Navigation("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
