// <auto-generated />
using System;
using ErpBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ErpBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502152129_AddCostPriceToProduct")]
    partial class AddCostPriceToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ErpBackend.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountTypeId = 1,
                            Code = "111",
                            IsActive = true,
                            Name = "Tiền mặt"
                        },
                        new
                        {
                            Id = 2,
                            AccountTypeId = 1,
                            Code = "112",
                            IsActive = true,
                            Name = "Tiền gửi ngân hàng"
                        },
                        new
                        {
                            Id = 3,
                            AccountTypeId = 1,
                            Code = "131",
                            IsActive = true,
                            Name = "Phải thu khách hàng"
                        },
                        new
                        {
                            Id = 4,
                            AccountTypeId = 1,
                            Code = "156",
                            IsActive = true,
                            Name = "Hàng hóa"
                        },
                        new
                        {
                            Id = 5,
                            AccountTypeId = 2,
                            Code = "331",
                            IsActive = true,
                            Name = "Phải trả người bán"
                        },
                        new
                        {
                            Id = 6,
                            AccountTypeId = 4,
                            Code = "511",
                            IsActive = true,
                            Name = "Doanh thu bán hàng"
                        },
                        new
                        {
                            Id = 7,
                            AccountTypeId = 5,
                            Code = "632",
                            IsActive = true,
                            Name = "Giá vốn hàng bán"
                        });
                });

            modelBuilder.Entity("ErpBackend.Entities.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccountTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tài sản (Asset)",
                            NormalBalance = "Debit"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nợ phải trả (Liability)",
                            NormalBalance = "Credit"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vốn chủ sở hữu (Equity)",
                            NormalBalance = "Credit"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Doanh thu (Revenue)",
                            NormalBalance = "Credit"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chi phí (Expense)",
                            NormalBalance = "Debit"
                        });
                });

            modelBuilder.Entity("ErpBackend.Entities.AlertNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AlertNotifications");
                });

            modelBuilder.Entity("ErpBackend.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasAnnotation("Relational:JsonPropertyName", "branch");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Cầu Giấy, Hà Nội",
                            Name = "Hà Nội",
                            Phone = "024.111.222"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Quận 1, TP.HCM",
                            Name = "Sài Gòn",
                            Phone = "028.333.444"
                        });
                });

            modelBuilder.Entity("ErpBackend.Entities.BranchStock", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("productId");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("branchId");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("quantity");

                    b.HasKey("ProductId", "BranchId");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchStocks");

                    b.HasAnnotation("Relational:JsonPropertyName", "branchStocks");
                });

            modelBuilder.Entity("ErpBackend.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCode")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ErpBackend.Entities.CustomerBranch", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomerId", "BranchId");

                    b.HasIndex("BranchId");

                    b.ToTable("CustomerBranches");
                });

            modelBuilder.Entity("ErpBackend.Entities.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExchangeRates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrencyCode = "USD",
                            Date = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rate = 25450.0m
                        },
                        new
                        {
                            Id = 2,
                            CurrencyCode = "EUR",
                            Date = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rate = 27120.0m
                        });
                });

            modelBuilder.Entity("ErpBackend.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            Name = "Kế toán kho Hà Nội"
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            Name = "Sales Hà Nội"
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 2,
                            Name = "Admin Sài Gòn"
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 1,
                            Name = "Admin Hà Nội"
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 2,
                            Name = "Sales Sài Gòn"
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 2,
                            Name = "Kế toán kho Sài Gòn"
                        });
                });

            modelBuilder.Entity("ErpBackend.Entities.GroupPermission", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("GroupPermissions");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            GroupId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            GroupId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            GroupId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            GroupId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            GroupId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            GroupId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            GroupId = 3,
                            PermissionId = 2
                        },
                        new
                        {
                            GroupId = 3,
                            PermissionId = 3
                        },
                        new
                        {
                            GroupId = 3,
                            PermissionId = 4
                        },
                        new
                        {
                            GroupId = 3,
                            PermissionId = 5
                        },
                        new
                        {
                            GroupId = 3,
                            PermissionId = 6
                        },
                        new
                        {
                            GroupId = 3,
                            PermissionId = 7
                        },
                        new
                        {
                            GroupId = 4,
                            PermissionId = 1
                        },
                        new
                        {
                            GroupId = 4,
                            PermissionId = 2
                        },
                        new
                        {
                            GroupId = 4,
                            PermissionId = 3
                        },
                        new
                        {
                            GroupId = 4,
                            PermissionId = 4
                        },
                        new
                        {
                            GroupId = 4,
                            PermissionId = 5
                        },
                        new
                        {
                            GroupId = 4,
                            PermissionId = 6
                        },
                        new
                        {
                            GroupId = 4,
                            PermissionId = 7
                        },
                        new
                        {
                            GroupId = 5,
                            PermissionId = 1
                        },
                        new
                        {
                            GroupId = 5,
                            PermissionId = 6
                        },
                        new
                        {
                            GroupId = 5,
                            PermissionId = 7
                        },
                        new
                        {
                            GroupId = 6,
                            PermissionId = 1
                        },
                        new
                        {
                            GroupId = 6,
                            PermissionId = 2
                        },
                        new
                        {
                            GroupId = 6,
                            PermissionId = 5
                        });
                });

            modelBuilder.Entity("ErpBackend.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmountVND")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ErpBackend.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("ErpBackend.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("ErpBackend.Entities.JournalEntryLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("JournalEntryLines");
                });

            modelBuilder.Entity("ErpBackend.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ErpBackend.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Xem sản phẩm",
                            Name = "product.view"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Thêm sản phẩm",
                            Name = "product.create"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Duyệt hóa đơn",
                            Name = "invoice.approve"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Xuất báo cáo",
                            Name = "report.export"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nhập kho",
                            Name = "stock.import"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Tạo hóa đơn",
                            Name = "invoice.create"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Thanh toán",
                            Name = "invoice.payment"
                        });
                });

            modelBuilder.Entity("ErpBackend.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExpenseAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IncomeAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinStockThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseAccountId");

                    b.HasIndex("IncomeAccountId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ErpBackend.Entities.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ProductId");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("ErpBackend.Entities.StockTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FromBranchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToBranchId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromBranchId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ToBranchId");

                    b.ToTable("StockTransfers");
                });

            modelBuilder.Entity("ErpBackend.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            Password = "123",
                            Role = "Sales",
                            Username = "sales_hn"
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 1,
                            Password = "123",
                            Role = "User",
                            Username = "kho_hn"
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 2,
                            Password = "123",
                            Role = "Manager",
                            Username = "manager_sg"
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 1,
                            Password = "123",
                            Role = "Manager",
                            Username = "manager_hn"
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 2,
                            Password = "123",
                            Role = "Sales",
                            Username = "sales_sg"
                        },
                        new
                        {
                            Id = 7,
                            BranchId = 2,
                            Password = "123",
                            Role = "User",
                            Username = "kho_sg"
                        });
                });

            modelBuilder.Entity("ErpBackend.Entities.UserGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroups");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            GroupId = 2
                        },
                        new
                        {
                            UserId = 3,
                            GroupId = 1
                        },
                        new
                        {
                            UserId = 4,
                            GroupId = 3
                        },
                        new
                        {
                            UserId = 5,
                            GroupId = 4
                        },
                        new
                        {
                            UserId = 6,
                            GroupId = 5
                        },
                        new
                        {
                            UserId = 7,
                            GroupId = 6
                        });
                });

            modelBuilder.Entity("ErpBackend.Entities.Account", b =>
                {
                    b.HasOne("ErpBackend.Entities.AccountType", "AccountType")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpBackend.Entities.Account", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AccountType");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ErpBackend.Entities.BranchStock", b =>
                {
                    b.HasOne("ErpBackend.Entities.Branch", "Branch")
                        .WithMany("BranchStocks")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpBackend.Entities.Product", "Product")
                        .WithMany("BranchStocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ErpBackend.Entities.CustomerBranch", b =>
                {
                    b.HasOne("ErpBackend.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpBackend.Entities.Customer", "Customer")
                        .WithMany("CustomerBranches")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ErpBackend.Entities.GroupPermission", b =>
                {
                    b.HasOne("ErpBackend.Entities.Group", "Group")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpBackend.Entities.Permission", "Permission")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("ErpBackend.Entities.Invoice", b =>
                {
                    b.HasOne("ErpBackend.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("ErpBackend.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Branch");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ErpBackend.Entities.InvoiceItem", b =>
                {
                    b.HasOne("ErpBackend.Entities.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpBackend.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ErpBackend.Entities.JournalEntry", b =>
                {
                    b.HasOne("ErpBackend.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("ErpBackend.Entities.JournalEntryLine", b =>
                {
                    b.HasOne("ErpBackend.Entities.Account", "Account")
                        .WithMany("JournalEntryLines")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpBackend.Entities.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("ErpBackend.Entities.Payment", b =>
                {
                    b.HasOne("ErpBackend.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("ErpBackend.Entities.Product", b =>
                {
                    b.HasOne("ErpBackend.Entities.Account", "ExpenseAccount")
                        .WithMany()
                        .HasForeignKey("ExpenseAccountId");

                    b.HasOne("ErpBackend.Entities.Account", "IncomeAccount")
                        .WithMany()
                        .HasForeignKey("IncomeAccountId");

                    b.Navigation("ExpenseAccount");

                    b.Navigation("IncomeAccount");
                });

            modelBuilder.Entity("ErpBackend.Entities.StockTransaction", b =>
                {
                    b.HasOne("ErpBackend.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("ErpBackend.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ErpBackend.Entities.StockTransfer", b =>
                {
                    b.HasOne("ErpBackend.Entities.Branch", "FromBranch")
                        .WithMany()
                        .HasForeignKey("FromBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpBackend.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpBackend.Entities.Branch", "ToBranch")
                        .WithMany()
                        .HasForeignKey("ToBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromBranch");

                    b.Navigation("Product");

                    b.Navigation("ToBranch");
                });

            modelBuilder.Entity("ErpBackend.Entities.UserGroup", b =>
                {
                    b.HasOne("ErpBackend.Entities.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpBackend.Entities.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErpBackend.Entities.Account", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("JournalEntryLines");
                });

            modelBuilder.Entity("ErpBackend.Entities.AccountType", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("ErpBackend.Entities.Branch", b =>
                {
                    b.Navigation("BranchStocks");
                });

            modelBuilder.Entity("ErpBackend.Entities.Customer", b =>
                {
                    b.Navigation("CustomerBranches");
                });

            modelBuilder.Entity("ErpBackend.Entities.Group", b =>
                {
                    b.Navigation("GroupPermissions");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("ErpBackend.Entities.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ErpBackend.Entities.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("ErpBackend.Entities.Permission", b =>
                {
                    b.Navigation("GroupPermissions");
                });

            modelBuilder.Entity("ErpBackend.Entities.Product", b =>
                {
                    b.Navigation("BranchStocks");
                });

            modelBuilder.Entity("ErpBackend.Entities.User", b =>
                {
                    b.Navigation("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
